#!/usr/bin/env ruby

class DirCompletion
  def initialize(command, dir)
    @home_dir = '~/'
    @command = command
    @dir = @home_dir + dir
  end

  def matches
    dirs.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def dirs
    `ls #{@dir}`.split("\n")
  end
end

puts DirCompletion.new(ENV["COMP_LINE"], ARGV[0]).matches
exit 0
