#!/bin/sh

# prepare project page branch for github gh-pages (http://pages.github.com/)

# check that index is clean (this operation loses uncommitted files)
# no uncommitted changes OR untracked files/dirs
if [ -n "$(git status --porcelain)" ] || [ -n "$(git ls-files --other --exclude-standard --directory)" ]
then
  echo "action cancelled: creating project page branch would destroy dirty or untracked content"
  exit 1
fi

# create clean root branch for project gh-pages
git symbolic-ref HEAD refs/heads/gh-pages
rm .git/index
git clean -fdx
