"" general configuation

" vim, not vi
set nocompatible

" files
set title     " show filename in terminal title
set hidden    " hide buffers instead of closing, preserving the buffer

" text width, wrap
set textwidth=80
set colorcolumn=81
set nowrap

" indentation
set autoindent    " always autoindent
set copyindent    " copy the previous indentation on autoindenting
set tabstop=2     " tab = 2 spaces
set softtabstop=2 " tab = 2 spaces (when deleting)
set shiftwidth=2  " number of spaces to use for autoindenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set expandtab     " spaces instead of tabs
set smarttab      " insert tabs on the start of a line according to
                  " shiftwidth, not tabstop

" spaces: show non-breaking (and mark long lines)
set list
set listchars=extends:#,nbsp:.

" navigation
set number        " number lines
set ruler         " show row, col of cursor

" search
set hlsearch      " highlight search
set incsearch     " reveal search incrementally as typed
set ignorecase    " case-insensitive match...
set smartcase     " ...except when uppercase letters are given

set backspace=indent,eol,start  " backspace over everything
set pastetoggle=<F2>            " for pasting verbatim

" folding
set foldlevelstart=2  " unfold top level at start

" memory
set history=1024    " number of commands, searches
set undolevels=1024 " number of mistakes

" persistence:
" marks for 128 recent files
" registers < 256 lines and < 10k in size
" ignore hlsearch state on start
set viminfo='128,<256,s10,h

" syntax highlighting
syntax on
colorscheme slate

" shell (bash, interactive)
set shell=/bin/bash\ -i

" unicode
set encoding=utf-8
setglobal fileencoding=utf-8

" spelling (w.o. capitalization check)
set spellfile=~/.vim/dict.add
set spellcapcheck=''

" no backups
set nobackup
set noswapfile
set backupskip=/tmp/*,/private/tmp/*

" no annoying beeps
set visualbell
set noerrorbells

" no mode (see airline)
set noshowmode

"" custom bindings

let mapleader=','       " map by , instead of /
let maplocalleader='\'  " map local by \

" command by ;
map ; :

" fast navigation
nmap <C-H> <C-W>h
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k
nmap <C-L> <C-W>l

" fast buffer alternation, next/prev, close
map ga <C-^>
nmap gn :bn<CR>
nmap gp :bp<CR>
nmap gk :bp<bar>bd #<CR>

" very magic search (sane regex)
" map / /\v

" clear search
nmap <silent> <leader>/ :nohlsearch<CR>

" fold/unfold
nmap <leader>z za

" wrap on Q, unwrap on C-Q
nmap Q gq
vmap Q gqa
nmap <C-Q> vipJ
vmap <C-Q> J

" case cycling
vmap ~ ygv"=TwiddleCase(@")<CR>Pgv

" spelling
nnoremap <silent> <leader>s :set spell!<CR>

" file explorer: tree view
let g:netrw_liststyle=3

" vim session save/load
nmap ss :wa<CR>:mksession! ~/.vim/sessions/
nmap so :wa<CR>:so ~/.vim/sessions/

" vim hacking convenience: edit, reload .vimrc
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

"" functions

" jump to pattern
function! Jump2Search(...)
  let pattern = a:1
  let flags = ''
  if a:0 > 1
    let flags = a:2
  endif
  call search(pattern, flags)
  norm zt
endfunction

" alternate among lower/title/upper case
function! TwiddleCase(str)
  if a:str ==# toupper(a:str)
    let result = tolower(a:str)
  elseif a:str ==# tolower(a:str)
    let result = substitute(a:str,'\(\<\w\+\>\)', '\u\1', 'g')
  else
    let result = toupper(a:str)
  endif
  return result
endfunction

" strip trailing whitespace
function! StripTrailing(...)
  let no_strip_types = []
  if a:0 > 0
    no_strip_types = a:1
  endif
  " save last search, cursor position
  let _s=@/
  let l = line('.')
  let c = col('.')
  if index(no_strip_types, &ft) < 0 " whitespace isn't evil for all files
    %s/\s\+$//e
  endif
  let @/=_s
  call cursor(l, c)
endfunction

"" automation

" file types
filetype on
filetype indent on
filetype plugin on

" strip trailing whitespace on save
let no_strip_types = ['diff', 'markdown', 'pandoc']
autocmd BufWritePre *.* call StripTrailing(no_strip_types)

"" plugins

" pathogen
call pathogen#infect()

" status (airline)
set laststatus=2
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.whitespace = 'Ξ'

" file finding (ctrlp)
let g:ctrlp_map = '<leader>t'
map <c-p>  :CtrlP getcwd()<CR>
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""' " silver searcher

" latex
let g:Tex_ViewRule_pdf = 'Skim'
"autocmd BufWritePost *.tex silent call Tex_RunLaTeX()

" lusty juggler: shorter shortcut
nmap <silent> <leader>j :LustyJuggler<CR>

" notes
let g:notes_directory = '~/h/notebook/jot'
let g:notes_suffix = '.md'
let g:notes_title_sync = 'rename_file'
let g:notes_smart_quotes = 1
let g:notes_list_bullets = ['*', '-', '+']

" paper reading
let g:papers_directory = '~/h/notebook/papers/'

" pandoc
let g:pandoc_no_spans = 1
let g:pandoc_use_hard_wraps = 1
"let g:pandoc_auto_format = 1
let g:pandoc_bibfiles = [g:papers_directory . 'library.bib']

" tabularize
nmap <leader>e :Tabularize /

" youcompleteme
" let g:ycm_key_list_select_completion = ['<TAB>', '<Down>']
" let g:ycm_filetype_blacklist = {
"       \ 'notes':1,
"       \ 'markdown':1,
"       \ 'pandoc':1,
"       \ 'text':1,
"       \ 'journal':1
"       \}
